import io
import ezdxf
from flask import Flask, request, send_file
from ezdxf.enums import TextEntityAlignment

app = Flask(__name__)

# Konfiguracja DIN
DIN_SIZES = {
    "a4": (297, 210),
    "a3": (420, 297),
    "a2": (594, 420),
    "a1": (841, 594),
    "a0": (1189, 841),
}

MARGIN = {"left": 25, "right": 10, "top": 10, "bottom": 10}

@app.route('/generate', methods=['POST'])
def generate():
    try:
        # Pobieranie danych z n8n
        data = request.get_json()
        if not data:
            return {"error": "Missing JSON body"}, 400
            
        size = data.get('size', 'a4').lower().strip()
        
        if size not in DIN_SIZES:
            return {"error": f"Size '{size}' not supported. Use a4, a3, etc."}, 400

        width, height = DIN_SIZES[size]
        
        # Tworzenie dokumentu DXF
        doc = ezdxf.new(dxfversion="R2010")
        doc.header["$INSUNITS"] = 4  # mm
        doc.header["$MEASUREMENT"] = 1 # metric
        
        msp = doc.modelspace()

        # 1. Ramka zewnętrzna (arkusz)
        msp.add_lwpolyline(
            [(0, 0), (width, 0), (width, height), (0, height)],
            close=True, dxfattribs={"lineweight": 18}
        )

        # 2. Ramka wewnętrzna (pole rysunkowe)
        fx, fy = MARGIN["left"], MARGIN["bottom"]
        fw = width - MARGIN["left"] - MARGIN["right"]
        fh = height - MARGIN["top"] - MARGIN["bottom"]
        
        msp.add_lwpolyline(
            [(fx, fy), (fx + fw, fy), (fx + fw, fy + fh), (fx, fy + fh)],
            close=True, dxfattribs={"lineweight": 50}
        )

        # 3. Tabliczka rysunkowa (180x55 mm)
        tb_w, tb_h = 180, 55
        tx, ty = fx + fw - tb_w, fy
        
        msp.add_lwpolyline(
            [(tx, ty), (fx + fw, ty), (fx + fw, ty + tb_h), (tx, ty + tb_h)],
            close=True, dxfattribs={"lineweight": 50}
        )

        # 4. Proste linie w tabliczce (podział na wiersze)
        for i in range(1, 6):
            y_line = ty + (i * 9)
            msp.add_line((tx, y_line), (fx + fw, y_line))

        # 5. Tekst informacyjny
        msp.add_text(
            f"FORMAT: {size.upper()}", 
            dxfattribs={"height": 5, "layer": "TEXT"}
        ).set_placement((tx + 5, ty + 40), align=TextEntityAlignment.LEFT)
        
        msp.add_text(
            "GENERATED BY N8N + RENDER", 
            dxfattribs={"height": 3.5}
        ).set_placement((tx + 5, ty + 10), align=TextEntityAlignment.LEFT)

        # --- KONWERSJA DO STREAMU ---
        # Zapisujemy DXF jako tekst do StringIO
        out_stream = io.StringIO()
        doc.write(out_stream)
        
        # Konwertujemy tekst na bajty dla n8n
        mem = io.BytesIO()
        mem.write(out_stream.getvalue().encode('utf-8'))
        mem.seek(0)
        out_stream.close()

        return send_file(
            mem,
            mimetype="application/dxf",
            as_attachment=True,
            download_name=f"template_{size}.dxf"
        )

    except Exception as e:
        return {"error": str(e)}, 500

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=10000)
